# litter.staging.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: lits
  name: lits
  namespace: staging-ragdoll
spec:
  ports:
    - name: "lits-port"
      port: 8891
      targetPort: lits-http
  selector:
    deployment.name: lits
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lits
  namespace: staging-ragdoll
spec:
  replicas: 1 # Update to 3 to get stateful proplems. Look at flash messages.
  selector:
    matchLabels:
      deployment.name: lits
  template:
    metadata:
      labels:
        deployment.name: lits
    spec:
      containers:
      - name: lits
        image: gitlab.lnu.se:5050/2dv013/student/team-2023-02-ragdoll/project-litter/lits
        # image: gitlab.lnu.se:5050/2dv013/student/sm223qi/part2-architecture/just-task-it-featuring-logging/litter # Update to your project url
        env:
        - name: DB_CONNECTION_STRING
          value: "mongodb://mongodb-lits-replicaset-0.mongodb-lits-replicaset-headless.staging-ragdoll.svc.cluster.local:27017,mongodb-lits-replicaset-1.mongodb-lits-replicaset-headless.staging-ragdoll.svc.cluster.local:27017,mongodb-lits-replicaset-arbiter-0.mongodb-lits-replicaset-arbiter-headless.staging-ragdoll.svc.cluster.local:27017/lits?replicaSet=rs0"
          # value: "mongodb://mongodb-lits:27020/lits"
        - name: PORT
          value: "3003"
        - name: ACCESS_TOKEN_PUBLIC
          valueFrom:
            secretKeyRef:
              name: auth-keys
              key: publicKey
        - name: RABBITMQ_PROTOCOL
          value: "amqp"
        - name: RABBITMQ_HOST
          value: "my-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_QUEUE_NAME
          value: "notificationQueue"
        - name: RABBITMQ_USERNAME
          value: "user"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-rabbitmq
              key: rabbitmq-password
        ports:
          - containerPort: 3003
            name: lits-http
      imagePullSecrets:
       - name: regcred # Secret set as a secret in the cluster

